version: 2
updates:
  # Configuration for frontend (React + Vite)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      dependencies:
        patterns:
          - "*"

  # Configuration for sanity (Sanity.io)
  - package-ecosystem: "npm"
    directory: "/sanity"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      dependencies:
        patterns:
          - "*"
