[build]
  command = "npm install --include=dev && NODE_ENV=production npm run build"
  publish = "dist/client"
  functions = "netlify/functions"


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"