[build]
  command = "npm install --include=dev && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.18.0"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200